### ISSUE TITLE
Confusing `m/and` matching

### ISSUE THREAD

**Issue by boxxxie** [noprompt/meander#112]
In the `and` documentation, and from my experience, and checks the first pattern for being matched, and then maybe considers the following patterns. i'm not sure how to use this pattern matcher, i would expect that if i put a bunch of patterns in an `(m/and ...)` that all would have to match to be successful. however, possibly this is the default behavior of pattern matching. i could use some help with `m/and m/or` in terms of examples and helping me figure out how they differ from logical `and/or`.

currently, if i want to do an and, i do something like the below

`(m/pred #(and (pred1? %) (pred2? %)) ?my-var)`

**Comment by jimmyhmiller** [comment]
Hey @boxxxie, 

I'm happy to clarify a bit about how and works. So let's start with your example.

```clojure
(m/match [4 6 8 10 30]
  [(m/and (m/pred even?) (m/pred #(> % 2)) !xs) ...]
  !xs)
```
So instead of doing `#(and ...)` you can use `m/and`.

But there are a lot of other reasons you might use `m/and`. The idea behind `m/and` is that you are matching multiple patterns on the same value. For example, maybe I want to save a value in a memory variable but also match with a logic variable.

```clojure
(m/match [4 [6 8 10 30] 4 [5 23 235 34]]
  [(m/and ?x !xs) [!xs ...] ?x [!xs ...]]
  [?x !xs])
```

`m/and` and `m/or` can really be thought of as just the pattern matching equivalent of the logical operators. With `m/and` all the patterns have to match. With `m/or` one of the patterns has to match.

Hopefully that helps some what, let me know if there is anything else I can explain to try and help. And feel free to join us on the clojurians slack to ask more questions :)

**Comment by boxxxie** [comment]
"With m/and all the patterns have to match."
the documentation does not say this, and in my experience, this is not the behavior.
only the first pattern has to match, and the rest are optional. which is why i'm not able to easily translate m/and to the logical and, becuase whenever i use it it only cares about my first pattern

i'm using the latest version of epsilon.

**Comment by boxxxie** [comment]
each of your examples uses memory variables, so maybe this is important for m/and m/or. i'm not actually familiar with memory variables because they are not in other pattern matchers i have used.

**Comment by jimmyhmiller** [comment]
@boxxxie 

Here is an example without memory variables that shows what I mean by all patterns have to match.

```clojure
(m/match 4
  (m/and (m/pred even?) (m/pred #(> % 3)) ?x)
  ?x)

;; => 4

(m/match 2
  (m/and (m/pred even?) (m/pred #(> % 3)) ?x)
  ?x)

;; =>  non exhaustive pattern match

```


Can you give an example where it is only using your first pattern?

**Comment by boxxxie** [comment]
yeah, i just wrote a tiny interpreter where m/and was failing, i'll rewrite one of the patterns in it to use m/and and post and example, likely tomorrow (just doing a ton of work right now)

**Comment by boxxxie** [comment]
```clojure
(let [test [[1] [2] [3]]]
  (assert (sequential? test))
  (assert (every? sequential? test))

  (assert
   (match [test]
     [(m/and (m/pred sequential?) (m/pred (p every? sequential?)) ?int-vars-vectors)]
     :all-lists))

  (assert
   (match [test]
     [(m/pred sequential? (p every? sequential?) ?int-vars-vectors)]
     :all-lists)))
```
ok, i got a simple test case. only the last assert fails, so i may be confused as to how `m/pred` works.

**Comment by jimmyhmiller** [comment]
Okay after looking through your code I'm guessing that `p` here is `partial`? If so, it seems that `m/and` is working as you expect, correct? As for `m/pred`, pred takes a single predicate and then some patterns. So your second example doesn't work because you are trying to use two predicates. If you want multiple predicates, the first example with and is the way to go, or you can combine predicates into one function.

So hopefully that clears things up? Is `m/and` still not working for you? 


That said I understand you were just giving some examples, but I do what to just show some more meander-y ways of saying these things. 

Let's take your first example. (I've changed it to return the logic variable because otherwise we didn't need it)

```clojure
(m/match [test]
    [(m/and (m/pred sequential?) (m/pred (partial every? sequential?)) ?int-vars-vectors)]
    ?int-vars-vectors)
```
We can transform this by getting rid of those extra `[]` because they aren't really needed.

```clojure
(m/match test
    (m/and (m/pred sequential?) (m/pred (partial every? sequential?)) ?int-vars-vectors)
    ?int-vars-vectors)
```

Now perhaps you really care that this is `sequential?` and not any other time, but let's ignore that for a second and say that we really know the outer thing is a vector and want to know if the inner things are sequential. Then we could write:

```clojure
(m/match test
  [(m/pred sequential?) ... :as ?int-vars-vectors]
  ?int-vars-vectors)
```

Or perhaps we aren't concerned with sequential, but just seqable, then we could use meanders built-in seqable operator.

```clojure
(m/match test
  (m/seqable (m/seqable _) ... :as ?int-vars-vectors)
  ?int-vars-vectors)
```

And finally perhaps what we really wanted to do was extract all those elements that were in our seqables, then we can grab them out with memory variables.

```clojure
(m/match test
  (m/seqable (m/seqable !xs) ...)
  !xs)
;; => [1 2 3]
```

I know this quite far afield from the example you gave, but I just wanted to model a bit of the meander way of looking at things. `m/pred` is great. But if you can use other things those are often better.

**Comment by boxxxie** [comment]
ok, my main misunderstanding was with m/pred argument differences between predicates and patterns.

thanks for the later examples, the vector wrapping i did is not important, just similar to the interoperater code the examples are based on.

m/seqable seems a bit under-documented, and in your example (last one), it's not fully clear how a memory variable should be different from a logic variable.

**Comment by jimmyhmiller** [comment]
You can read a bit more about memory variables here: https://cljdoc.org/d/meander/epsilon/0.0.402/doc/operator-overview#memory-variables

Memory variables remember the values they match and are really useful when combined with repeats. You can see more about practical uses here as well https://jimmyhmiller.github.io/meander-practical.

We definitely could improve documentation on seqable. That is one of those perpetual things. We never have enough documentation and its hard to ensure we keep things up to date. It's great that we've had a growing community that can help in that regard.

I am going to go ahead and close this issue. I'm still happy to help in any way I can. And like I mentioned before, the clojurians slack #meander channel is a great place to get help from others.

Cheers
