### ISSUE TITLE
pattern matching syntax for (m/some) in maps

### ISSUE THREAD

**Issue by boxxxie** [noprompt/meander#122]
one of my more common use cases for meander is something like spec/asserts for config loading.

```clojure
(defmethod ig/init-key :prototype.gateway/vhost.debug [_ opts]
  (match opts
    {
     :vhost {
             :scheme ?scheme
             :host   ?host
             }
     }
    (do
      (assert ?scheme)
      (assert ?host)
      #_code
)))
```
it would be nice if i didn't have to wrap all my symbol captures in `(m/some ...)` because that pollutes the pattern shape. and i rather not have to write a macro to convert a meander thing into a spec of some sort.

syntax proposal:
```clojure
(match opts
    {
     :vhost {
             :scheme $scheme
             :host   $host
             }
     })
```

i don't really care how the syntax looks, but it seems like a lot of the symbols are already taken.

**Comment by noprompt** [comment]
@boxxxie This is something I've also encountered and thought about a bit and, to be honest, am still thinking about. It really goes back to my original decision to put the constraint on map keys, rather than on the values, because "optional" stuff is all the rage in Clojure, and you can't tell the different between `(get {} :k)` and `(get {:k nil} :k)` without using `find` or `contains?` to check if `:k` is there or not.

One thing I've done, and something you could try, might go like

```clj
(m/defsyntax vhost [{:keys [scheme host]}]
  (m/match [scheme host]
    [nil nil] {}
    [___ nil] {:scheme `(m/some ~scheme)}
    [nil ___] {:host `(m/some ~host)}
    _  {:scheme `(m/some ~scheme), :host `(m/some ~host)}
```

and then

```clj
(m/match opts
  {:vhost (vhost {:scheme ?scheme, :host ?host})}
  code)
```

If you have many cases like this, you could generalize this a bit with

```clj
(m/defsyntax strict-map [x]
  (m/match x
    {}
    (reduce-kv
     (fn [m k v]
       (assoc m k `(m/some ~v)))
     {}
     x)

    _
    `(m/and {} ~x)))
```

and then

```clj
(m/match opts
  {:vhost (strict-map {:scheme ?scheme
                       :host ?host})}

  code)
```

I know this isn't as lightweight as `$scheme`, however, it does suck out those `m/some`s which can be pretty ugly when you have many of them.

**Comment by boxxxie** [comment]
looks cool, i'm guessing that i can do this with clojure.walk, to make something more general?
i haven't used the syntax part of meander yet

**Comment by noprompt** [comment]
@boxxxie I probably wouldn't use `clojure.walk` for something like `strict-map` because the definition is already sufficient (though I now realize it needs to be modified it to handle `:as`). As soon as you use anything other other than a variable, `nil`, or a combination of patterns that represent some non-variable, non-nil value you don't need to wrap that thing in `m/some` any more because it's implied by the pattern.

```clj
{:k [& _]} ;; val is a vector
{:k (& _)} ;; val is a seq
{:k {}} ;; val is a map
{:k #{}} ;; val is a set
```

One nice thing to point out about definition of `strict-map` is that you can still have "optional keys" by using `&`:

```clj
(m/match opts
  {:vhost (strict-map {:scheme ?scheme
                       :host ?host
                       & {:doc ?doc}})}
  ;;                   ^^^^^^^^^^^^^ `?doc` can be `nil`
  code)
```

**Comment by boxxxie** [comment]
i didn't know about the ` & {}` syntax

**Comment by noprompt** [comment]
@boxxxie Have a look [here](https://github.com/noprompt/meander/blob/epsilon/doc/operator-overview.md#rest) for more details.

**Comment by noprompt** [comment]
Closing pending a plan of action.
