### ISSUE TITLE
Syntax Extensions must be qualified when using in another ns

### ISSUE THREAD

**Issue by lucywang000** [noprompt/meander#145]
I was debugging some code that involves custom defsyntax, just to find that the culprit is, if I have a custom syntax `foo-syntax` defined in ns `foo`, and want to use it in `bar`, I have to always use `foo/foo-syntax` (or `foo-alias/foo-syntax` if I'm aliasing the `foo` ns name), even if I have `:require [foo :refer [foo-syntax]]` in bar's ns declaration. 

Is this expected behavior? If so we shall document it explicitly.

foo.clj
```clojure
(ns foo
  (:require [meander.epsilon :as me]))

(me/defsyntax gen-map
  "Shorthand for the map spread syntax

   (gen-map !k !v) would expand to:

   {& ([!k !v] ...)}

   (me/rewrite [1 2 3 4]
   [!xs !ys ...]
   (gen-map !xs !ys))
   ;; => {1 2, 3 4}"
  [!k !v]
  `{~'& ([~!k ~!v] ~'...)})
```

bar.clj
```clojure
(ns bar
  (:require [meander.epsilon :as me]
            [foo :refer [gen-map]]))


(me/rewrite [1 2 3 4]
  [!xs !ys ...]
  (gen-map !xs !ys))
;; => (gen-map 1 2)

(me/rewrite [1 2 3 4]
  [!xs !ys ...]
  (foo/gen-map !xs !ys))
;; => {1 2, 3 4}

(me/rewrite [1 2 3 4]
  [!xs !ys ...]
  (~gen-map !xs !ys))
;; => (#function[foo/gen-map] 1 2)
```

**Comment by noprompt** [comment]
@lucywang000 The symbol resolution for syntax extensions relies on `meander.util.epsilon/expand-symbol`. I think the [Clojure resolution](https://github.com/noprompt/meander/blob/epsilon/src/meander/util/epsilon.cljc#L576-L581) could probably be changed to use `clojure.core/resolve` and then get the symbol from the var if it exists, otherwise leave the symbol untouched. I'm a little busy at the moment and won't be able to look at this until later today. If you're able to find a patch, don't hesitate to open a pull request.

**Comment by lucywang000** [comment]
> the Clojure resolution could probably be changed to use clojure.core/resolve and then get the symbol from the var if it exists, otherwise leave the symbol untouched. 

That sounds brilliant! what about the cljs side? Is there a way to check whether a symbol has an alias in the current ns?

**Comment by noprompt** [comment]
@lucywang000 I've patched this and will now make a release. See #146 for the code details.
