### ISSUE TITLE
Why do some map patterns accept any map?

### ISSUE THREAD

**Issue by AdamNiederer** [noprompt/meander#15]
Hello, I noticed some interesting behavior using `meander.match.alpha/match` and `meander.match.alpha/search` - it looks like any given map pattern will accept a map regardless of the keys in the pattern.

```clojure
meander-test.core> (meander.match.alpha/match {:name "bob" :color "yellow"}
                     {:something _a} :fail
                     {:name _b :color _c} :ok)
:fail ; Unexpected - would expect :ok
```

Is this intended behavior? I would guess from the documentation that map patterns will only accept maps with a superset of the keys in the pattern.

It looks like it behaves as I would expect when literal map values are used in the pattern, but not keys. (using search because it allows variables as map keys):

```clojure
meander-test.core> (meander.match.alpha/search [{:x 2} {:y 3}]
                     (scan {?a 2}) :two-val
                     (scan {?b 3}) :three-val)
(:two-val :three-val) ; Expected
```

```clojure
meander-test.core> (meander.match.alpha/search [{:x 2} {:y 3}]
                     (scan {:x ?a}) :x-key
                     (scan {:y ?b}) :y-key)
(:x-key :x-key :y-key :y-key) ; Unexpected - would expect (:x-key :y-key)
```

Thanks a bunch - this library looks incredibly powerful and useful. Apologies if I'm missing something.

**Comment by noprompt** [comment]
> Is this intended behavior? 

Yes, this is by design and it should be explained in the README. Map patterns have semantics close to `{:keys [,,,]}` destructuring *up to* key value pairs where the key is ground and the value is a variable. Here is a search demonstrating each of these cases.

```clj
(r.match/search {}
  {:k1 _1, :k2 _2}
  [:a]

  {:k1 ?k1, :k2 ?k2}
  [:b ?k1 ?k2]

  {:k1 !ks, :k2 !ks}
  [:c !ks])
;; =>
([:a] [:b nil nil] [:c [nil nil]]) 
```

If you look at the macro expansion (don't 😄) you'll notice `get` is used to pull the values and the variables are then bound to them since the first case doesn't care about the values, the second case has no previously bound occurrences of `?k1` or `?k2`, and memory variables match and collect everything. Originally the match compiler used `find` against maps to both ensure membership and pull the value (which I thought was the right idea). However, in practice I found it made map patterns in many situations awkward and frustrating to use. So I relaxed the compilation and compromised on placing a constraint on the key's value which, I think, works well and is the path of least resistance in a world of optional keys.

Here's what I mean.

```clj
(r.match/search {:k1 10, :k2 12}
  {:k1 (pred number? _1)
   :k2 (pred number? _2)}
  [:a]

  {:k1 (pred number? ?k1)
   :k2 12}
  [:b ?k1]

  {:k1 (pred odd? !ks)
   :k2 (pred odd? !ks)}
  [:c !ks])
;; =>
([:a] [:b 10])
```

> Apologies if I'm missing something.

No apology necessary. Actually, I really like it when people ask questions like this because it gives me an opportunity to explain some of the rational while at the same time illuminating where documentation could be improved.

Please let me know if this was helpful and if you have more questions, do ask them. 👍

**Comment by AdamNiederer** [comment]
Thanks for the in-depth explanation - that was exceedingly helpful! I hadn't thought of composing different patterns in that way - with the ability to do that, the current setup makes a lot more sense. Thanks again!
