### ISSUE TITLE
Match against JavaScript objects in ClojureScript

### ISSUE THREAD

**Issue by timothypratley** [noprompt/meander#20]
It would be nice to support:

```
(match x
  #js {:key ?val} ;; Match a js/Object
  ?val
  #js [?x ?y] ;; Match a js/Array
  (+ ?x ?y))
```

Then we can destructure JS objects yay

**Comment by noprompt** [comment]
This is complete and available in `[meander/beta "0.0.29"]`. Sadly, my hopes of being able to use `search` with patterns like `#js {?k ?v}` were crushed by the ClojureScript reader which demands only string or unqualified keyword keys. Oh well. A way around this would be to create another form that can work around this limitation. That being said, I wrote the code anyway so that when such a form is added it'll just work. 😄
