### ISSUE TITLE
Reflection warning in util/epsilon.cljc, field val

### ISSUE THREAD

**Issue by SevereOverfl0w** [noprompt/meander#201]
```
❯ clj -Sdeps '{:deps {meander/epsilon {:mvn/version "0.0.650"}}}'
Downloading: meander/epsilon/0.0.650/epsilon-0.0.650.pom from clojars
Downloading: meander/epsilon/0.0.650/epsilon-0.0.650.jar from clojars
Clojure 1.10.3
user=> (require '[meander.epsilon :as m])
Reflection warning, meander/util/epsilon.cljc:758:24 - reference to field val can't be resolved.
```

**Comment by noprompt** [comment]
@vemv Are you able to figure this one out? This is connected to the (awesome) work you did a while back. I'm not quite sure what to do.

**Comment by vemv** [comment]
Will check it out, appreciate the repro as well 👍

**Comment by vemv** [comment]
So I believe this is not a realistic reflection warning to experience. If you're using `val-of-js-value` then `cljs.tagged_literals.JSValue` should be in the classpath.

The reason why `Reflection warning, meander/util/epsilon.cljc:758:24 - reference to field val can't be resolved` is printed is because https://github.com/noprompt/meander/blob/501c7d1d1079cb275f11d0476bab6c31c9b37dc9/src/meander/util/epsilon.cljc#L10 is performed.

I'd recommend against `(set! *warn-on-reflection* true)`, [here's](https://github.com/clojure-emacs/clj-refactor.el/issues/485#issuecomment-907795057) an explanatory rant (and suggested alternatives)

Cheers - V

**Comment by noprompt** [comment]
@vemv Thanks for the prompt reply and advice! I'm in favor of removing the check. 👍

**Comment by noprompt** [comment]
This has been patched and will go out with the next version of the library!
