### ISSUE TITLE
Transforming values with functions via containment contexts

### ISSUE THREAD

**Issue by AdamNiederer** [noprompt/meander#22]
Hello!

I've been playing around with the new containment (recursive scan?) pattern from the [gamma release notes](https://github.com/noprompt/meander/commit/fc0800e40561a7a570bb9ada24d7e79a04d85e5a), and I was curious if there was a way to use a context to replace a value by transforming it with a function, rather than replacing it outright.

For example, I'm currently able to write this:

```clojure
;; Replace all 5s with 0s
meander-test.core> (mat/search [1 [2 3] [4 [[5] 6]] [7 8 [9]]]
                     ($ ?context 5)
                     (?context 0))
([1 [2 3] [4 [[0] 6]] [7 8 [9]]])
```

and I'm curious if there's a way to do something like this:

```clojure
;; Stringify all 5s
meander-test.core> (mat/search [1 [2 3] [4 [[5] 6]] [7 8 [9]]]
                     ($* ?context 5)
                     (?context str))
([1 [2 3] [4 [["5"] 6]] [7 8 [9]]])
```

I think [this bit](https://github.com/noprompt/meander/blob/gamma/src/meander/match/gamma.cljc#L428) suggests that it may not be possible, but I figured I'd ask anyway.

Thanks for continuing to develop this library; I'm always finding new ways to do useful things with it!

**Comment by noprompt** [comment]
Oh, I like that! It has an almost applicative feel to it. Also wouldn't take much effort to implement. It'd probably be worthwhile to mediate on what the substitution semantics would be (if such exist). One thing I've been very interested in is having match and substitution patterns be inverses of each other such that a rewrite rule where the left and the right sides are the same pattern is semantically equivalent to the identity function. For example,

```clj
(rewrite
  ($ ?context ?x) ;; Matches ?x in subtree, binds ?context fn.
  ($ ?context ?x)) ;; Applies ?context to ?x to produce the original tree.
```
and

```clj
(rewrite
   [!xs !ys ...] ;; Collect !xs and !ys
   [!xs !ys ...]) ;; Disperse !xs and !ys
```

and

```clj
(rewrite
  {:x ?x & ?rest-map} ;; Bind ?rest-map to the dissoc of :x
  {:x ?x & ?rest-map} ;; Assoc :x into ?rest-map
```

have this property.

Of course, this isn't true for all patterns and isn't a hard must for this library. I'm just bringing it up as something to think about because it's very powerful property both in theory and in practice. In this case I'm wondering if there's a way to define the `$*` so that it could also be an inverse to match under substitution. Again, it's not a must if there isn't a way to pull it off but if we can come up with something that'd be awesome.

I'd be curious to hear a little bit more about the motivation from your perspective if you have time to detail your thinking. Sometimes that teases out other interesting tangents that help solidify these things.

**Comment by timothypratley** [comment]
After re-reading that thread and the release notes, I think my use case is a good example :slightly_smiling_face:

I’ll try to write up a more formal description, but basically justice is:

    (:a ?x) => [?x :a ?result]
    (rule ?x) => (rule ?x ?result)
    [head (or clause1 clause2)] => [head clause] [head clause]
    [head (and clause1 clause2)] => [head clause clause]

And being able to go from DataScript to Justice and Justice to DataScript both have utility.
The reason I need to write it up more formally is the various conditionals around `:my/_attribute` reverses the relation etc.

My initial thought is that a function makes complete sense, and if that is possible I also wonder if there is a way to say "For this substitution, the dual of str is parse-int" because I'd love to go in the other direction as well.

**Comment by timothypratley** [comment]
Is this code equivalent of `$*` ??:

```
(mat/search [1 [2 3] [4 [[5] 6]] [7 8 [9]]]
            ($ ?context (and ?x 5))
            (?context (str ?x)))
;=> [1 [2 3] [4 [["5"] 6]] [7 8 [9]]]
```

Or as a strategy:

```
((m/rewrite ($ ?context (and ?x 5))
            ($ ?context ~(str ?x)))
  [1 [2 3] [4 [[5] 6]] [7 8 [9]]])
;=> [1 [2 3] [4 [["5"] 6]] [7 8 [9]]]
```

But is not symmetrical with substitution:
```
((m/rewrite ($ ?context (and ?x 5))
            ($ ?context (and ?x 5)))
;=> [1 [2 3] [4 [[(and 5 5)] 6]] [7 8 [9]]]
```

**Comment by timothypratley** [comment]
Said another way, I think that any pattern `(and ?x 5)` should be substituted as 5.

**Comment by noprompt** [comment]
@AdamNiederer Apologies for the long pause between the time you opened this issue and now. I'm happy to say this will be easily achievable in the next release of Meander: `epsilon`. I haven't released my notes and details yet about the next arm of the project, however, the branch is publicly accessible if you want to try out the following.

First — and perhaps you've figured this out — you can actually emulate `$*` as described using `and`, as Tim showed, and `let` which is the other piece of the puzzle.

```clj
(search [1 [2 3] [4 [[5] 6]] [7 8 [9]]]
  (and ($ ?context* (and 5 ?pattern))
       (let ?context (fn [f] (?context* (f ?pattern)))))
  (?context str))
;; =>
([1 [2 3] [4 [["5"] 6]] [7 8 [9]]])
```

We can even take it a little further by making that `?context` function do a bit more.

```clj
(search [1 [2 3] [4 [[5] 6]] [7 8 [9]]]
  (and ($ ?context* (and 5 ?pattern))
       (let ?context (fn
                       ([]
                        ;; Identity.
                        (?context* ?pattern))
                       ([f]
                        ;; Apply function to value then put back.
                        (?context* (f ?pattern)))
                        ;; Apply function to value with args then put
                        ;; back.
                       ([f & args]
                        (?context* (apply f ?pattern args))))))
  (?context str ",000"))
;; =>
([1 [2 3] [4 [["5,000"] 6]] [7 8 [9]]])
```

Which is really cool but kind of a pain to reuse. You can use `defsyntax` for this on the `delta` arm but the `epsilon` arm separates match and substitution parsing in cleaner ways. Anyhow, here's what a rough sketch of the syntax extension looks like:

```clj
(r.match.syntax/defsyntax $* [context pattern]
  `(~'and (~'$ ?context# (~'and ~pattern ?pattern#))
    (~'let ~context (fn
                      ([]
                       (?context# ?pattern#))
                      ([f#]
                       (?context# (f# ?pattern#)))
                      ([f# & args#]
                       (?context# (apply f# ?pattern# args#)))))))
```

`r.match.syntax` is an alias for the new `meander.match.syntax.<greek>` namespace. After I define this in my namespace I can use it as a pattern matching operator.

```clj
(search [1 [2 3] [4 [[5] 6]] [7 8 [9]]]
  ($* ?context 5)
  (?context str ",000"))
;; =>
([1 [2 3] [4 [["5,000"] 6]] [7 8 [9]]])
```

Since the `epsilon` branch also allows substitution syntax to be extended, it should be possible to make a version of `$*` for that.

**Comment by noprompt** [comment]
I added this on the `epsilon` branch.
