### ISSUE TITLE
Got errors on require meander

### ISSUE THREAD

**Issue by lvrg-acc** [noprompt/meander#76]
Hi there, stumbled upon this error. Am I doing something wrong?

```
lein try meander/epsilon "0.0.201"

nREPL server started on port 56408 on host 127.0.0.1 - nrepl://127.0.0.1:56408
REPL-y 0.4.3, nREPL 0.6.0
Clojure 1.10.0
Java HotSpot(TM) 64-Bit Server VM 10+46
    Docs: (doc function-name-here)
          (find-doc "part-of-name-here")
  Source: (source function-name-here)
 Javadoc: (javadoc java-object-or-class-here)
    Exit: Control+D or (exit) or (quit)
 Results: Stored in vars *1, *2, *3, an exception in *e

user=> (require '[meander.epsilon :as m])
Syntax error (ClassNotFoundException) compiling at (epsilon.cljc:1:1).
java/sql/Timestamp

```

**Comment by noprompt** [comment]
@RomanTsopin It is not clear based on this information whether the problem is with Meander.

Are you able to reproduce the error with only Clojure and Meander as dependencies?

If you have `clj` installed, try

```
clj -Sdeps '{:deps {meander/epsilon {:mvn/version "0.0.201"}}}'
```

Followed by

```clj
(require '[meander.epsilon :as m])
```

Considering the error it seems unlikely Meander is the culprit.

**Comment by lvrg-acc** [comment]
Yes, that works, thank you!
Interesting that I haven't seen similar problems with other libraries. Maybe it's some erroneous plugin behaviour. I guess the issue could be closed.

**Comment by jimmyhmiller** [comment]
I'll see if I can recreate it later today. Even if it is not only meanders fault it is worth knowing what is causing the breakage. It could be lein try or something in your lein user profile. If you can share that that would be great.

**Comment by lvrg-acc** [comment]
Here's ~/.lein/profiles.clj 
` {:user {:plugins [[lein-try "0.4.3"]]}}`

**Comment by jimmyhmiller** [comment]
@RomanTsopin I just tried this with your same profile and at first was not able to reproduce.

But I was on an older jdk, switch to jdk13 and was able to reproduce. I can verify this isn't a meander issue though, you can see this issue here for more about what is going on. https://github.com/technomancy/leiningen/issues/2149

You can see that there are lots of different issues around this. Honestly, not 100% sure the right way to fix your problem right now, but hopefully this does show this is a lein/jdk issue not a meander one.
